// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/api-docs/Current.tsx": () => import("../components/mockups/api-docs/Current.tsx"),
  "./components/mockups/api-docs/Reorganized.tsx": () => import("../components/mockups/api-docs/Reorganized.tsx"),
  "./components/mockups/settlements/Current.tsx": () => import("../components/mockups/settlements/Current.tsx"),
  "./components/mockups/settlements/Improved.tsx": () => import("../components/mockups/settlements/Improved.tsx")
};
